---
- name: Install packages we care about
  become: yes
  become_method: sudo
  yum:
    update_cache: yes
    name: "{{ packages }}"
  vars:
    packages:
      - bison
      - flex
      - git-core
      - e2fsprogs
      - xfsprogs
      - xfsdump
      - lvm2
      - gcc
      - make
      - gawk
      - bc
      - dump
      - libtool
      - psmisc
      - sed
      - vim
      - fio
      - libaio-devel
      - diffutils
      - net-tools
      - ncurses-devel
      - xfsprogs
      - e2fsprogs
      - btrfs-progs
      - elfutils-libelf-devel
      - ntfs-3g
      - mdadm
      - rpcbind
      - portmap
      - hwinfo
      - iscsi-initiator-utils
      - openssl
      - openssl-devel
      - dwarves
      - zstd

- name: Remove packages that mess with initramfs
  become: yes
  become_method: sudo
  yum:
    state: absent
    name: dracut-config-generic
