---
# Install dependenciesfor oscheck on Red Hat based systems
- name: Refresh cache and upgrade all present packages
  become: yes
  become_method: sudo
  yum:
    update_cache: yes
    name: '*'
    state: latest
  when:
    - devconfig_try_upgrade|bool

- name: Reboot system to make the new kernel and modules take effect
  become: yes
  become_method: sudo
  reboot:
  when:
    - devconfig_try_upgrade|bool

- name: Build install package list
  set_fact:
    packages:
      - bison
      - flex
      - git-core
      - e2fsprogs
      - xfsprogs
      - btrfs-progs
      - xfsdump
      - lvm2
      - gcc
      - make
      - gawk
      - bc
      - dump
      - libtool
      - psmisc
      - sed
      - vim
      - fio
      - libaio-devel
      - diffutils
      - net-tools
      - ncurses-devel
      - openssh-server
      - net-snmp

- name: Add GNU screen to install package list
  set_fact:
    packages: "{{ packages + [ 'screen' ] }}"
  when:
    ansible_facts['os_family']|lower != 'redhat' or ansible_facts['distribution_major_version'] | int < 8

- name: Add Tmux to install package list
  set_fact:
    packages: "{{ packages + [ 'tmux' ] }}"
  when:
    ansible_facts['os_family']|lower == 'redhat' or ansible_facts['distribution_major_version'] | int >= 8

- name: Install packages we typically care about
  become: yes
  become_method: sudo
  yum:
    update_cache: yes
    name: "{{ packages }}"
  when:
    - devconfig_try_install_kdevtools|bool

- name: Set up snmp
  become: yes
  become_method: sudo
  template:
    src: snmpd.conf
    dest: /etc/snmp/snmpd.conf
  when:
    - devconfig_try_install_kdevtools|bool
  tags: snmpd

- name: Set up snmp
  become: yes
  become_method: sudo
  template:
    src: snmpd.conf
    dest: /etc/snmp/snmpd.conf
  when:
    - devconfig_try_install_kdevtools|bool
  tags: snmpd

- name: Enable snmpd service
  become: yes
  become_method: sudo
  systemd:
    name: snmpd
    enabled: yes
    masked: no
  tags: snmpd

- name: Start snmpd service
  become: yes
  become_method: sudo
  systemd:
    name: snmpd
    state: restarted
  tags: snmpd
